### ISSUE TITLE
Hidden meaning

### ISSUE THREAD

**Issue by szepeviktor** [valorin/random#6]
In the description

> Random is a simple helper package designed to make it easy to generate a range of different cryptographically secure random values.

there is a long _preamble_ (telling nothing)

> Random is a simple helper package designed to make it easy to generate a range of different

then the juicy stuff

> cryptographically secure random values

My recommendation is to tell about the package in the beginning.

"Generate cryptographically secure random values ..."

**Comment by valorin** [comment]
I'd argue that 'simple helper package' does tell something - i.e. it's not a horribly complex package, but something simple and easy to use. However, I do take your point that _cryptographically secure random values_ is the most important bit.

How does this sound:

> Random generates cryptographically secure random values in a range of different formats through a simple helper package for PHP.
